import { Component } from "@angular/core";
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { InAppBrowser } from "@ionic-native/in-app-browser";
import { IonicPage, NavController, NavParams } from "ionic-angular";
import { GlobalSettingsProvider } from "../../providers/global-settings/global-settings";

/**
 * Generated class for the LoginPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: "page-login",
  templateUrl: "login.html",
})
export class LoginPage {

  public node: string = "/accounts/login?pib_mobile=true";

  // Page URL is generated by appending the node to the global site URL.
  public pageUrl: SafeUrl;

  constructor(public navCtrl: NavController, public navParams: NavParams, private sanitizer: DomSanitizer,
              private globalSettingsProvider: GlobalSettingsProvider) {

    const siteUrl = globalSettingsProvider.siteUrl();
    const url = siteUrl + this.node;
    this.pageUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
