import { Component, Renderer2 } from "@angular/core";
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { InAppBrowser } from "@ionic-native/in-app-browser";
import { NativeStorage } from "@ionic-native/native-storage";
import { IonicPage, NavController, NavParams, Platform } from "ionic-angular";
import { GlobalSettingsProvider } from "../../providers/global-settings/global-settings";
import { HomePage } from "../home/home";

import { GooglePlus } from "@ionic-native/google-plus";
import { Toast } from "@ionic-native/toast";

/**
 * Generated class for the LoginPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: "page-login",
  templateUrl: "login.html",
})
export class LoginPage {

  public node: string = "/accounts/login?pib_mobile=true";

  // Page URL is generated by appending the node to the global site URL.
  public pageUrl: SafeUrl;

  constructor(private platform: Platform, public navCtrl: NavController, public navParams: NavParams,
              private sanitizer: DomSanitizer, private renderer: Renderer2, private nativeStorage: NativeStorage,
              private toast: Toast, private iab: InAppBrowser,
              private globalSettingsProvider: GlobalSettingsProvider, private googlePlus: GooglePlus) {

    const siteUrl = globalSettingsProvider.siteUrl();
    const url = siteUrl + this.node;
    this.pageUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);

    this.platform.ready().then(() => {
      const messageListener = this.renderer.listen(window, "message", (evt) => {
        this.receiveMessage(evt);
      });
    });

  }

  public receiveMessage(event) {
    console.log("receiving message: " + event.data);
    if (event.data === "googleLogin") {
      this.doGoogleLogin();
    } else if (event.data === "facebookLogin") {
      this.doFacebookLogin();
    }
  }

  public doGoogleLogin() {
    console.log("googleLogin");
    this.iab.create(this.globalSettingsProvider.siteUrl() + "/accounts/google/login/?process=");
  }

  public doFacebookLogin() {
    console.log("facebookLogin");
    this.iab.create(this.globalSettingsProvider.siteUrl() + "/accounts/facebook/login/?process=");
  }
}
