import { Component, Renderer2 } from "@angular/core";
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { InAppBrowser } from "@ionic-native/in-app-browser";
import { IonicPage, Platform, NavController, NavParams } from "ionic-angular";
import { GlobalSettingsProvider } from "../../providers/global-settings/global-settings";
import { HomePage } from "../home/home";

import { GooglePlus } from "@ionic-native/google-plus";

/**
 * Generated class for the LoginPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: "page-login",
  templateUrl: "login.html",
})
export class LoginPage {

  public node: string = "/accounts/login?pib_mobile=true";

  // Page URL is generated by appending the node to the global site URL.
  public pageUrl: SafeUrl;

  constructor(private platform: Platform, public navCtrl: NavController, public navParams: NavParams, private sanitizer: DomSanitizer,
              private renderer: Renderer2,
              private globalSettingsProvider: GlobalSettingsProvider, private googlePlus: GooglePlus) {

    const siteUrl = globalSettingsProvider.siteUrl();
    const url = siteUrl + this.node;
    this.pageUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);

    this.platform.ready().then(() => {
      let messageListener = this.renderer.listen(window, 'message', (evt) => {
        this.receiveMessage(evt); 
      });
    })


  }

  receiveMessage(event) {
    console.log("receiving message: " + event.data);
    if (event.data === 'googleLogin') {
      this.doGoogleLogin();
    } else if (event.data === 'facebookLogin') {
      console.log('facebookLogin');
    }
  }

  doGoogleLogin() {
    console.log('googleLogin');
    let nav = this.navCtrl;
    let env = this;
    this.googlePlus.login({
      'scopes': '', // optional, space-separated list of scopes, If not included or empty, defaults to `profile` and `email`.
      'webClientId': '1090448644110-r8o52h1sqpbq7pp1j8ougcr1e35qicqg.apps.googleusercontent.com', // optional clientId of your Web application from Credentials settings of your project - On Android, this MUST be included to get an idToken. On iOS, it is not required.
      'offline': true
    })
    .then(function (user) {  
      this.nativeStorage.setItem('user', {
        name: user.displayName,
        email: user.email,
        picture: user.imageUrl
      })
      .then(function(){
        nav.push(HomePage);
      }, function (error) {
        console.log(error);
      })
    }, function (error) {
      console.log(error);
    });
  }
}
