import { Component, ViewChild } from "@angular/core";
import { DomSanitizer, SafeUrl } from "@angular/platform-browser";
import { NativeAudio } from "@ionic-native/native-audio";
import { NavController, Platform } from "ionic-angular";
import { GlobalSettingsProvider } from "../../providers/global-settings/global-settings";

@Component({
  selector: "page-home",
  templateUrl: "home.html",
})
export class HomePage {

  public node: string = "/curriculum?pib_mobile=true";

  // Page URL is generated by appending the node to the global site URL.
  public pageUrl: SafeUrl;
  public navbarIcon: string = "menu";

  @ViewChild("mainObject") public mainObject: any;
  public mainObjectElement: any;

  constructor(public navCtrl: NavController, public platform: Platform,
              public globalSettingsProvider: GlobalSettingsProvider, private sanitizer: DomSanitizer,
              private nativeAudio: NativeAudio) {

    const backAction =  platform.registerBackButtonAction(() => {
      this.mainObjectElement.contentWindow.postMessage("goBack", "*");
      console.log("second");
      backAction();
    }, 2);

    const siteUrl = globalSettingsProvider.siteUrl();
    const url = siteUrl + this.node;
    this.pageUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);

    window.addEventListener("message", (event) => {
      console.log(event.data);
      if (event.data === "pagePushed") {
        this.pagePush();
      } else if (["audioComplete", "audioContinue", "audioCorrect", "audioDoubleRainbow", "audioExamCorrect",
      "audioExamStart", "audioIncorrect"].indexOf(event.data) > -1) {
        console.log(event.data);
        this.nativeAudio.play(event.data).then(null, (error) => {
          console.log(error);
      });
      }
    });
  }

  public ngAfterViewInit() {
    this.mainObjectElement = this.mainObject.nativeElement;
  }

  public pagePush() {
    console.log("pagePushed");
    this.navbarIcon = "arrow-back";
  }
}
