import { Component, ViewChild } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { GlobalSettingsProvider } from '../../providers/global-settings/global-settings';
import { SafeUrl, DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  node: string = "/curriculum?pib_mobile=true";

  // Page URL is generated by appending the node to the global site URL.
  pageUrl: SafeUrl;

  @ViewChild('mainObject') mainObject: any;
  mainObjectElement: any;

  constructor(public navCtrl: NavController, public platform: Platform, public globalSettingsProvider: GlobalSettingsProvider,
    private sanitizer: DomSanitizer) {

    let backAction =  platform.registerBackButtonAction(() => {
      this.mainObjectElement.contentWindow.postMessage('goBack', '*');
      console.log("second");
      backAction();
    }, 2);

    const siteUrl = globalSettingsProvider.siteUrl();
    const url = siteUrl + this.node;
    this.pageUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }

  ngAfterViewInit() {
    this.mainObjectElement = this.mainObject.nativeElement;
  }
}
